name: DarkSquare
favicon: null
layout_spectrum: 0.9314998700283468
typography_spectrum: 0.76366799720563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.17972782417200506
  lightness: 0.7820367142558098
  saturation: 0.09229389321990311
  rhythmicContrast: 0.7779404881875962
purpose: []
