name: DarkSquare
favicon: null
layout_spectrum: 0.9314998700283468
typography_spectrum: 0.76366799720563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191616'
    - '#110e0e'
    - '#241d1c'
    - '#2e2724'
    - '#383836'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.7779404881875962
purpose: []
